### ISSUE TITLE
Precomputed loss

### ISSUE THREAD

**Issue by kno10** [motiwari/BanditPAM#164]
A workaround for #163 would be if I could simply provide a precomputed loss matrix, and use "precomputed" loss.

I couldn't find the doxygen documentation online anywhere, the available losses appear to be here:

https://github.com/ThrunGroup/BanditPAM/blob/5f12c07d80101abf076eea32a313bba9dbf427c8/src/kmedoids_algorithm.cpp#L129

**Comment by motiwari** [comment]
I like the proposed solution, as supporting sparse matrices natively would be significantly more complicated

**Comment by kno10** [comment]
It does increase the run time with the quadratic cost of the similarity matrix though.
