### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by rheinonen** [motiwari/BanditPAM#188]
The test scripts depend on files called 'MNIST_70k.csv' and 'scrna_reformat.csv.gz.' Unfortunately, these seem to be missing from the repo, so the tests don't run.

**Comment by motiwari** [comment]
Sorry for the extremely late response. The necessary data files are available from my website, e.g., https://github.com/motiwari/BanditPAM/blob/main/scripts/docker/env_setup.sh#L27 . 

We haven't shipped them with the repo so users don't have to download huge files they don't need if they're not running the tests.
