### ISSUE TITLE
`max_iter` not being passed correctly from Python

### ISSUE THREAD

**Issue by motiwari** [motiwari/BanditPAM#235]

**Comment by Adarsh321123** [comment]
Closing this as `max_iter` is being passed correctly from Python. Here are some more details:

I built the C++ code on an Ubuntu VM running on a Windows laptop and then built the Python with `pip install .` I then ran a simplified version of `test_smaller.py` with just the `test_small_mnist_known_cases` test. I was able to log the `max_iter` reached by C++ and confirm that it is the same as that passed to the `fit` method of a `KMedoids` object in Python.
