### ISSUE TITLE
pip install on windows doesn't use MS Visual C++ compiler

### ISSUE THREAD

**Issue by Dobatymo** [motiwari/BanditPAM#242]
In the Windows Python world the MS Visual C++ compiler is definitely the default compiler used and also the one used to compile the official Python distribution. It should be supported by default.

```
Exception: No C++ compiler was found. Please install LLVM clang.
```

**Comment by motiwari** [comment]
Thanks for filing an issue! 

@Adarsh321123 let's discuss this
